language: python
python:
  - "2.7"
env:
  - DJANGO=1.7 DB=sqlite3
install:
  - pip install -r requirements.txt --use-mirrors
script:
  - export DJANGO_SETTINGS_MODULE=pymg.settings.test
  - python manage.py syncdb --noinput
  - python manage.py test
